### ISSUE TITLE
Cannot install arcgisrest2spatialite from setup.py

### ISSUE THREAD

**Issue by ghost** [napo/arcgisrest2spatialite#2]
I'm trying to install arcgisrest2spatialite from source. I cloned the repo, but when I run the command "python setup.py install" I received an error:

C:\Users\ivn\Desktop\repo>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to arcgis_rest_to_spatialite.egg-info\requires.txt
writing arcgis_rest_to_spatialite.egg-info\PKG-INFO
writing top-level names to arcgis_rest_to_spatialite.egg-info\top_level.txt
writing dependency_links to arcgis_rest_to_spatialite.egg-info\dependency_links.txt
reading manifest file 'arcgis_rest_to_spatialite.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'arcgis_rest_to_spatialite.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
installing scripts to build\bdist.win32\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
**error: file 'C:\Users\ivn\Desktop\repo\arcgis2splite.py' does not exist**

**Comment by napo** [comment]
thanks for the issue
Now should be ok
Can you check?
